services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true
    environment:
      - TZ=Australia/Sydney
      - dbhost=${DATABASE_HOST}
      - dbuser=${DATABASE_USER}
      - dbpass=${DATABASE_PASSWORD}
      - igdbclientid=${IGDB_CLIENT_ID}
      - igdbclientsecret=${IGDB_CLIENT_SECRET}
  mariadb:
    hostname: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_DB}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
